#pragma once

#include <SDL.h>

#define KEY_Q SDLK_q
#define KEY_W SDLK_w
#define KEY_E SDLK_e
#define KEY_R SDLK_r
#define KEY_T SDLK_t
#define KEY_Y SDLK_y
#define KEY_U SDLK_u
#define KEY_I SDLK_i
#define KEY_O SDLK_o
#define KEY_P SDLK_p
#define KEY_A SDLK_a
#define KEY_S SDLK_s
#define KEY_D SDLK_d
#define KEY_F SDLK_f
#define KEY_G SDLK_g
#define KEY_H SDLK_h
#define KEY_J SDLK_j
#define KEY_K SDLK_k
#define KEY_L SDLK_l
#define KEY_Z SDLK_z
#define KEY_X SDLK_x
#define KEY_C SDLK_c
#define KEY_V SDLK_v
#define KEY_B SDLK_b
#define KEY_N SDLK_n
#define KEY_M SDLK_m
#define KEY_1 SDLK_1
#define KEY_2 SDLK_2
#define KEY_3 SDLK_3
#define KEY_4 SDLK_4
#define KEY_5 SDLK_5
#define KEY_6 SDLK_6
#define KEY_7 SDLK_7
#define KEY_8 SDLK_8
#define KEY_9 SDLK_9
#define KEY_0 SDLK_0
#define KEY_CTRL SDLK_LCTRL
#define KEY_ALT SDLK_LALT
#define KEY_LSHIFT SDLK_LSHIFT
#define KEY_RSHIFT SDLK_RSHIFT
#define KEY_EXCLAIM SDLK_EXCLAIM
#define KEY_AT SDLK_AT
#define KEY_HASH SDLK_HASH
#define KEY_DOLLAR SDLK_DOLLAR
#define KEY_PERCENT SDLK_PERCENT
#define KEY_CARET SDLK_CARET
#define KEY_AMPERSAND SDLK_AMPERSAND
#define KEY_ASTERISK SDLK_ASTERISK
#define KEY_HYPHEN SDLK_MINUS
#define KEY_UNDERSCORE SDLK_UNDERSCORE
#define KEY_PLUS SDLK_PLUS
#define KEY_MINUS SDLK_MINUS
#define KEY_EQUALS SDLK_EQUALS
#define KEY_UP_ARROW SDLK_UP
#define KEY_DOWN_ARROW SDLK_DOWN
#define KEY_LEFT_ARROW SDLK_LEFT
#define KEY_RIGHT_ARROW SDLK_RIGHT
#define KEY_SPACEBAR SDLK_SPACE
#define KEY_BACKSPACE SDLK_BACKSPACE
#define KEY_ENTER SDLK_RETURN
#define KEY_TAB SDLK_TAB
